/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InfoRequest } from '../../models/info-request';
import { InfoResponse } from '../../models/info-response';

export interface AuthManageInfoPost$Params {
      body: InfoRequest
}

export function authManageInfoPost(http: HttpClient, rootUrl: string, params: AuthManageInfoPost$Params, context?: HttpContext): Observable<StrictHttpResponse<InfoResponse>> {
  const rb = new RequestBuilder(rootUrl, authManageInfoPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InfoResponse>;
    })
  );
}

authManageInfoPost.PATH = '/auth/manage/info';
