/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BoatData } from '../models/boat-data';
export interface BoatDetail {
  data: BoatData;
  id: string;
}
