/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AccessTokenResponse } from './models/access-token-response';
export type { BoatCreateRequest } from './models/boat-create-request';
export type { BoatData } from './models/boat-data';
export type { BoatDetail } from './models/boat-detail';
export type { ForgotPasswordRequest } from './models/forgot-password-request';
export type { HttpValidationProblemDetails } from './models/http-validation-problem-details';
export type { InfoRequest } from './models/info-request';
export type { InfoResponse } from './models/info-response';
export type { LoginRequest } from './models/login-request';
export type { RefreshRequest } from './models/refresh-request';
export type { RegisterRequest } from './models/register-request';
export type { ResendConfirmationEmailRequest } from './models/resend-confirmation-email-request';
export type { ResetPasswordRequest } from './models/reset-password-request';
export type { TwoFactorRequest } from './models/two-factor-request';
export type { TwoFactorResponse } from './models/two-factor-response';
