/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AuthService } from './services/auth.service';
export { BoatsService } from './services/boats.service';
